# Generated by Django 4.2.4 on 2023-08-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='size',
            field=models.PositiveIntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Large')]),
        ),
    ]
