# Generated by Django 4.2.4 on 2023-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_egg_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
