# Generated by Django 4.2.4 on 2023-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_chicken_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
