# Generated by Django 4.2.4 on 2023-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_egg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='health_status',
            field=models.PositiveIntegerField(choices=[(0, 'Healthy'), (1, 'Sick'), (99, 'Dead')]),
        ),
    ]
