# Generated by Django 4.2.4 on 2023-08-14 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0006_chicken_date_added_chicken_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicken',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EggShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateField()),
                ('customer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('eggs', models.ManyToManyField(to='crm.egg')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
