# Generated by Django 4.2.4 on 2023-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_eggshipment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='quantity',
        ),
    ]
